name: "@title@"
author: "@author@"
date: "@date@"
version: "@version@"
url: "@url@"
rundeckPluginVersion: 2.0
description: Execution Mode Later Plugin UI
rundeckCompatibilityVersion: 3.2.x
targetHostCompatibility: all
license: Apache 2.0
tags:
    - script
    - UI
providers:
    - name: "@name@"
      service: UI
      title: "@title@"
      description: "@description@"
      plugin-type: ui
      ui:
        - pages: '*'
          scripts:
            - "js/init.js"
            - "js/executionMode.js"
            - "js/editProject.js"
          styles:
            - css/execution-mode-later-ui-styles.css
